### ISSUE TITLE
how to install this repository

### ISSUE THREAD

**Issue by infinZero** [jaydenpung/lotterymachine#1]
can you plz help me, how I can implement this in my code? lets say I want to display this into flutter app, is there any direct plugin to use this in flutter? or I'll have to install this on website page and then display that page in flutter webview? please help me all

**Comment by jaydenpung** [comment]
Hi, there is no direct plugin available. You may implement this on your own or just use the native js script as shown [here](https://www.jaypung.com/#/portfolio/work-luckyball.html)
